### ISSUE TITLE
Awaiting Documentation for Review

### ISSUE THREAD

**Issue by kmh654** [mantha3806/CamoProject#1]
Hi guys, I'll be your unruly Tigers Rep.

**Comment by mantha3806** [comment]
Hey, not sure what documents we need to post on here?

**Comment by mantha3806** [comment]
documents are up

**Comment by kmh654** [comment]
Thanks for the documents, however unfortunately this is less than 48 hours notice, and less then 24 hours for construction of the product. Thank you for your time and effort but we will be unable to reproduce your product in the limited time frame.
